name: test1
on: 
  issues:
    action:
      close
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Update GitHub Profile README
        uses: theboi/github-update-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subhead: "latest issue closed by: '${{ github.actor }}'"
    
