name: test
on: 
  create:
    types:
      - label
      - issue
jobs:
  clabel_issues:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        run: '${{ github.event_name }}'
      - name: User
        run: '${{ github.actor }}'
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
       
